In [113]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in .\env\Lib\site-packages (2.4.2)
Requirement already satisfied: pandas in .\env\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in .\env\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\env\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\env\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [114]:
import numpy as np
import pandas as pd

In [115]:
# url = "........"
# data = pd.read_csv(url, encoding='latin1')
# data.head()

In [116]:
data = pd.read_csv('laptop_price.csv', encoding = 'latin1')
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [117]:
data.shape

(1303, 12)

In [118]:
data.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [119]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   str
 2   Product           1303 non-null   str
 3   TypeName          1303 non-null   str
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   str
 6   Cpu               1303 non-null   str
 7   Ram               1303 non-null   str
 8   Gpu               1303 non-null   str
 9   OpSys             1303 non-null   str
 10  Weight            1303 non-null   str
 11  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), str(9)
memory usage: 122.3 KB

In [120]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94

In [121]:
data['Ram'] = data['Ram'].str.replace('GB','').astype('int32')
data['Weight'] = data['Weight'].str.replace('kg','').astype('float32')

In [122]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94

In [123]:
data.corr(numeric_only=True)['Price_euros']

laptop_ID      0.067830
Inches         0.068197
Ram            0.743007
Weight         0.210370
Price_euros    1.000000
Name: Price_euros, dtype: float64

In [124]:
data['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

In [125]:
def add_company(inpt):
    if inpt == 'Samsung' or inpt == 'Razer' or inpt == 'Mediacom' or inpt == 'Microsoft' or inpt == 'Xiaomi' or inpt == 'Vero' or inpt == 'Chuwi' or inpt == 'Google' or inpt == 'Fujitsu' or inpt == 'LG' or inpt == 'Huawei':
        return 'Other'
    else:
        return inpt

data['Company'] = data['Company'].apply(add_company)

In [126]:
data['Company'].value_counts()

Company
Dell       297
Lenovo     297
HP         274
Asus       158
Acer       103
MSI         54
Other       51
Toshiba     48
Apple       21
Name: count, dtype: int64

In [127]:
data['Product'].value_counts()

Product
XPS 13                                30
Inspiron 3567                         29
250 G6                                21
Legion Y520-15IKBN                    19
Vostro 3568                           19
                                      ..
X541NA-GO020T (N3350/4GB/1TB/W10)      1
Rog G752VT-GC073T                      1
B51-80 (i7-6500U/8GB/1008GB/Radeon     1
GE62 Apache                            1
Yoga 500-14IBD                         1
Name: count, Length: 618, dtype: int64

In [128]:
data['TypeName'].value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64

In [129]:
data['ScreenResolution'].value_counts()

ScreenResolution
Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
IPS Panel 1366x768                                 7
Touchscreen 2560x1440                              7
4K Ultra HD 3840x2160                              7
IPS Panel Retina Display 2560x1600                 6
IPS Panel Retina Display 2304x1440                 6
Touchscreen 2256x1504                              6
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Touchscreen 2560x1440                    5
1440x900                                           4
IPS Panel Retina Display 2880x1800                 4
IPS Panel Touchscreen 1920x1200                    4
IPS Panel 2560x1440                                4
Touchscreen 2400x1600                              3
2560x1440                                          3
IPS Panel Quad HD+ 2560x1440                       3
IPS Panel Touchscreen 1366x768                     3
1920x1080                                          3
Quad HD+ 3200x1800                                 3
IPS Panel Full HD 2160x1440                        2
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
Touchscreen / Quad HD+ 3200x1800                   1
IPS Panel Full HD 1366x768                         1
IPS Panel Full HD 2560x1440                        1
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 1920x1200                        1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [130]:
data['Touchscreen'] = data['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0)
data['Ips'] = data['ScreenResolution'].apply(lambda x:1 if 'IPS' in x else 0)

In [131]:
data.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,575.00,0,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,2537.45,0,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,0,1

In [132]:
data['Cpu'].value_counts()

Cpu
Intel Core i5 7200U 2.5GHz              190
Intel Core i7 7700HQ 2.8GHz             146
Intel Core i7 7500U 2.7GHz              134
Intel Core i7 8550U 1.8GHz               73
Intel Core i5 8250U 1.6GHz               72
                                       ...
Intel Core i5 7200U 2.7GHz                1
Intel Pentium Dual Core 4405Y 1.5GHz      1
Intel Core M 6Y54 1.1GHz                  1
Samsung Cortex A72&A53 2.0GHz             1
AMD E-Series 9000 2.2GHz                  1
Name: count, Length: 118, dtype: int64

In [133]:
data['cpu_name']= data['Cpu'].apply(lambda x : " ".join(x.split()[0:3]))

In [134]:
data['cpu_name'].value_counts()

cpu_name
Intel Core i7               527
Intel Core i5               423
Intel Core i3               136
Intel Celeron Dual           80
Intel Pentium Quad           27
Intel Core M                 19
AMD A9-Series 9420           12
AMD A6-Series 9220            8
Intel Celeron Quad            8
AMD A12-Series 9720P          7
Intel Atom x5-Z8350           5
Intel Atom x5-Z8550           4
AMD A8-Series 7410            4
AMD Ryzen 1700                3
Intel Pentium Dual            3
AMD A9-Series 9410            3
AMD E-Series E2-9000e         2
Intel Xeon E3-1505M           2
AMD A10-Series A10-9620P      2
AMD A6-Series A6-9220         2
AMD A10-Series 9600P          2
AMD A10-Series 9620P          2
AMD E-Series 7110             2
AMD A9-Series A9-9420         2
Intel Xeon E3-1535M           2
Intel Atom X5-Z8350           2
Intel Atom x5-Z8300           1
AMD E-Series E2-6110          1
AMD FX 9830P                  1
AMD E-Series 6110             1
AMD E-Series 9000e            1
AMD Ryzen 1600                1
AMD E-Series E2-9000          1
AMD A6-Series 7310            1
Intel Atom Z8350              1
AMD A12-Series 9700P          1
AMD A4-Series 7210            1
AMD FX 8800P                  1
Samsung Cortex A72&A53        1
AMD E-Series 9000             1
Name: count, dtype: int64

In [135]:
def set_processor(name):
    if name == 'Intel Core i7' or name == 'Intel Core i5' or name == 'Intel Core i3' :
        return name
    else:
        if name.split()[0] == 'AMD':
            return 'AMD'
        else:
            return 'Other'

data['cpu_name'] = data['cpu_name'].apply(set_processor)

In [136]:
data['cpu_name'].value_counts()

cpu_name
Intel Core i7    527
Intel Core i5    423
Other            155
Intel Core i3    136
AMD               62
Name: count, dtype: int64

In [137]:
data['Gpu'].value_counts()

Gpu
Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
Nvidia Quadro M500M          1
AMD Radeon R7 M360           1
Nvidia Quadro M3000M         1
Nvidia GeForce 960M          1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [138]:
data['gpu_name']= data['Gpu'].apply(lambda x: " ".join(x.split()[0:1]))

In [139]:
data['gpu_name'].value_counts()

gpu_name
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [140]:
data.shape

(1303, 16)

In [141]:
data= data[data['gpu_name']!= 'ARM']

In [142]:
data.shape

(1302, 16)

In [143]:
data['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [144]:
def set_os(inpt):
    if inpt == 'Windows 10' or inpt == 'Windows 7' or inpt == 'Windows 10 S':
        return 'Windows'
    elif inpt == 'macOS' or inpt == 'Mac OS X':
        return 'Mac'
    elif inpt == 'Linux':
        return inpt
    else:
        return 'Other'

data['OpSys'] = data['OpSys'].apply(set_os)

In [145]:
data['OpSys'].value_counts()

OpSys
Windows    1125
Other        94
Linux        62
Mac          21
Name: count, dtype: int64

In [146]:
data.head(2)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,Ips,cpu_name,gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,Mac,1.37,1339.69,0,1,Intel Core i5,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,Mac,1.34,898.94,0,0,Intel Core i5,Intel

In [147]:
data = data.drop(columns = ['laptop_ID', 'Inches', 'Product', 'ScreenResolution', 'Cpu', 'Gpu'])

In [148]:
data.head()

,Company,TypeName,Ram,OpSys,Weight,Price_euros,Touchscreen,Ips,cpu_name,gpu_name
0,Apple,Ultrabook,8,Mac,1.37,1339.69,0,1,Intel Core i5,Intel
1,Apple,Ultrabook,8,Mac,1.34,898.94,0,0,Intel Core i5,Intel
2,HP,Notebook,8,Other,1.86,575.00,0,0,Intel Core i5,Intel
3,Apple,Ultrabook,16,Mac,1.83,2537.45,0,1,Intel Core i7,AMD
4,Apple,Ultrabook,8,Mac,1.37,1803.60,0,1,Intel Core i5,Intel

In [150]:
data = pd.get_dummies(data)      ##make more columns with numeriacal values for those columns that have string values

In [151]:
data.head()

,Ram,Weight,Price_euros,Touchscreen,Ips,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,...,OpSys_Other,OpSys_Windows,cpu_name_AMD,cpu_name_Intel Core i3,cpu_name_Intel Core i5,cpu_name_Intel Core i7,cpu_name_Other,gpu_name_AMD,gpu_name_Intel,gpu_name_Nvidia
0,8,1.37,1339.69,0,1,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
1,8,1.34,898.94,0,0,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
2,8,1.86,575.00,0,0,False,False,False,False,True,...,True,False,False,False,True,False,False,False,True,False
3,16,1.83,2537.45,0,1,False,True,False,False,False,...,False,False,False,False,False,True,False,True,False,False
4,8,1.37,1803.60,0,1,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [152]:
data.shape

(1302, 32)

In [153]:
x = data.drop('Price_euros', axis =1)
y = data['Price_euros']

In [156]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in .\env\Lib\site-packages (from scikit-learn) (2.4.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 1.7 MB/s eta 0:00:05
   --- ------------------------------------ 0.8/8.1 MB 1.6 MB/s eta 0:00:05
   ------ --------------------------------- 1.3/8.1 MB 1.8 MB/s eta 0:00:04
   --------- ------------------------------ 1.8/8.1 MB 1.9 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.1 MB 1.9 MB/s eta 0:00:04
   ------------ --------------------------- 2.6/8.1 MB 2.0 MB/s eta 0:00:03
   ---------------- ----------------------- 3.4/8.1 MB 2.2 MB/s eta 0:00:03
   ------------------- -------------------- 3.9/8.1 MB 2.3 MB/s eta 0:00:02
   ----------------------- ---------------- 4.7/8.1 MB 2.4 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.1 MB 2.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.1 MB 2.7 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 2.8 MB/s  0:00:02
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
    --------------------------------------- 0.8/36.6 MB 4.2 MB/s eta 0:00:09
   - -------------------------------------- 1.3/36.6 MB 3.4 MB/s eta 0:00:11
   -- ------------------------------------- 2.1/36.6 MB 3.6 MB/s eta 0:00:10
   --- ------------------------------------ 2.9/36.6 MB 3.7 MB/s eta 0:00:10
   ---- ----------------------------------- 3.7/36.6 MB 3.8 MB/s eta 0:00:09
   ----- ---------------------------------- 4.7/36.6 MB 4.0 MB/s eta 0:00:09
   ----- ---------------------------------- 5.2/36.6 MB 3.8 MB/s eta 0:00:09
   ------ --------------------------------- 6.3/36.6 MB 3.9 MB/s eta 0:00:08
   ------- -------------------------------- 7.1/36.6 MB 3.9 MB/s eta 0:00:08
   -------- ------------------------------- 7.9/36.6 MB 4.0 MB/s eta 0:00:08
   --------- ------------------------------ 8.9/36.6 MB 4.0 MB/s eta 0:00:07
   ---------- ----------------------------- 9.7/36.6 MB 4.0 MB/s eta 0:00:07
   ----------- ---------------------------- 10.2/36.6 MB 3.9 MB/s eta 0:00:07
   ----------- ---------------------------- 10.5/36.6 MB 3.8 MB/s eta 0:00:07
   ------------ --------------------------- 11.5/36.6 MB 3.7 MB/s eta 0:00:07
   ------------- -------------------------- 12.6/36.6 MB 3.8 MB/s eta 0:00:07
   -------------- ------------------------- 13.4/36.6 MB 3.9 MB/s eta 0:00:07
   --------------- ------------------------ 13.9/36.6 MB 3.9 MB/s eta 0:00:06
   ---------------- ----------------------- 14.9/36.6 MB 3.8 MB/s eta 0:00:06
   ----------------- ---------------------- 16.0/36.6 MB 3.9 MB/s eta 0:00:06
   ------------------ --------------------- 17.0/36.6 MB 3.9 MB/s eta 0:00:05
   ------------------- -------------------- 17.8/36.6 MB 4.0 MB/s eta 0:00:05
   -------------------- ------------------- 18.9/36.6 MB 4.0 MB/s eta 0:00:05
   --------------------- ------------------ 19.9/36.6 MB 4.0 MB/s eta 0:00:05
   ---------------------- ----------------- 20.7/36.6 MB 4.0 MB/s eta 0:00:04
   ----------------------- ---------------- 21.8/36.6 MB 4.1 MB/s eta 0:00:04
   ------------------------ --------------- 22.5/36.6 MB 4.1 MB/s eta 0:00:04
   ------------------------- -------------- 23.6/36.6 MB 4.1 MB/s eta 0:00:04
   -------------------------- ------------- 24.6/36.6 MB 4.1 MB/s eta 0:00:03
   --------------------------- ------------ 25.4/36.6 MB 4.1 MB/s eta 0:00:03
   ---------------------------- ----------- 26.5/36.6 MB 4.2 MB/s eta 0:00:03
   ------------------------------ --------- 27.5/36.6 MB 4.2 MB/s eta 0:00:03
   ------------------------------ --------- 28.3/36.6 MB 4.2 MB/s eta 0:00:02
   -------------------------------- ------- 29.4/36.6 MB 4.2 MB/s eta 0:00:02
   --------------------------------- ------ 30.4/36.6 MB 4.2 MB/s eta 0:00:02
   ---------------------------------- ----- 31.2/36.6 MB 4.2 MB/s eta 0:00:02
   ---------------------------------- ----- 32.0/36.6 MB 4.2 MB/s eta 0:00:02
   ----------------------------------- ---- 32.8/36.6 MB 4.2 MB/s eta 0:00:01
   ------------------------------------ --- 33.0/36.6 MB 4.2 MB/s eta 0:00:01
   ------------------------------------ --- 33.3/36.6 MB 4.1 MB/s eta 0:00:01
   ------------------------------------ --- 33.8/36.6 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 34.1/36.6 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/36.6 MB 4.0 MB/s eta 0:00:01
   -------------------------------------- - 35.1/36.6 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 35.7/36.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 3.8 MB/s  0:00:09
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

In [158]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [159]:
X_train.shape, X_test.shape

((976, 31), (326, 31))

In [164]:
def model_acc(model):
    model.fit(X_train, y_train)
    acc = model.score(X_test, y_test)
    print(str(model)+' --> '+ str(acc))

In [167]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model_acc(lr)

from sklearn.linear_model import Lasso
lasso = Lasso()
model_acc(lasso)

from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
model_acc(dt)

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
model_acc(rf)

LinearRegression() --> 0.7340672939512776
Lasso() --> 0.7306408763703351
DecisionTreeRegressor() --> 0.7362725809789635
RandomForestRegressor() --> 0.7904901641528917

In [170]:
from sklearn.model_selection import  GridSearchCV

parameters = {'n_estimators':[10, 50, 100],
             'criterion':['squared_error', 'absolute_error', 'poisson']}

grid_obj = GridSearchCV(estimator =rf , param_grid= parameters)

grid_fit= grid_obj.fit(X_train, y_train)

best_model = grid_fit.best_estimator_
best_model

RandomForestRegressor(criterion='absolute_error', n_estimators=10)

In [171]:
best_model.score(X_test, y_test)

0.768330276659335

In [172]:
import pickle
with open('predictor.pickle', 'wb') as file:
    pickle.dump(best_model, file)

In [173]:
X_train.columns

Index(['Ram', 'Weight', 'Touchscreen', 'Ips', 'Company_Acer', 'Company_Apple',
       'Company_Asus', 'Company_Dell', 'Company_HP', 'Company_Lenovo',
       'Company_MSI', 'Company_Other', 'Company_Toshiba',
       'TypeName_2 in 1 Convertible', 'TypeName_Gaming', 'TypeName_Netbook',
       'TypeName_Notebook', 'TypeName_Ultrabook', 'TypeName_Workstation',
       'OpSys_Linux', 'OpSys_Mac', 'OpSys_Other', 'OpSys_Windows',
       'cpu_name_AMD', 'cpu_name_Intel Core i3', 'cpu_name_Intel Core i5',
       'cpu_name_Intel Core i7', 'cpu_name_Other', 'gpu_name_AMD',
       'gpu_name_Intel', 'gpu_name_Nvidia'],
      dtype='str')

In [175]:
best_model.predict([[8, 1.3, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,0, 1,0, 1, 0, 0,1, 0, 0, 0, 0,1, 0, 1, 0, 0]])

C:\Users\User\Desktop\Laptop Price Predictor\model\env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1474.537])